### ISSUE TITLE
How can I replace the network with another network?

### ISSUE THREAD

**Issue by siyuan2018** [Time0o/pytorch-colorful-colorization#38]
Thanks very much for sharing the pytorch code for this work! I have a question here: how can I replace the network to another network, like vgg 16? Please guide me which ".py" file I should modify to use my network, also other things I need to pay attention to. 

Hope to hear form you, thanks!

**Comment by Time0o** [comment]
If you take a look at `colorization_network.py`, there's a part in the constructor where `self.base_network` is set to either a VGG or DeepLabV3Plus network. You could write your own network inheriting from `nn.Module` that has the same input and output dimensions as those two.
