### ISSUE TITLE
Input ab channels of ground-truth image for recovering the ground-truth.

### ISSUE THREAD

**Issue by SUNJIMENG** [Time0o/pytorch-colorful-colorization#45]
Thank you for sharing your code. 
I have a question:
I observed that if I input the ab channels of the ground-truth image, and operate SoftEncodeAB and AnnealedMeanDecodeQ successively, then I get ab_actual and concat with the input L. But the result is totally different from the ground-truth image and not colorful.  It seems wrong but I don't know why. 

The code, the recovered image, and the ground-truth image are shown here.
Hope to hear from you, thanks!
![image](https://user-images.githubusercontent.com/49275561/144584251-fe02a650-080b-4930-a8fb-29d66553ba8e.png)
![recover_gt](https://user-images.githubusercontent.com/49275561/144584355-d292167f-decd-4d24-a430-42dce9a57a93.png)
![gt](https://user-images.githubusercontent.com/49275561/144584383-7c80d54f-7342-41ee-b7ad-64f6bbd84aac.jpg)

**Comment by Time0o** [comment]
Are you using the pretained weights? You can try running the `predict_color` function in `colorization/util/image.py` for a pretrained network and an arbitrary image represented as a numpy array. If that works you can compare it to your code and post a minimal reproducible example if it still doesn't work as expected.
